# Integer Linear Programming Solver

Optimization Problem: Select 10 articles to display on the news feed that must have 
- More-than-average number of images, videos, and links
- At least two 'Others' articles to balance dominancee of other common topics
- At least three different categories are displayed

In [1]:
import pandas as pd 
import numpy as np
import os
import pulp

import sys
sys.path.append('/workspaces/news-promotion-lp')
from src.data.preprocess import load_data, preprocess_features
from src.optimization.lp_solver import news_solver, extended_news_solver
from src.models.train import *
from src.models.predict import *

## Dataset process

We will use the test dataset with predicted shares as input for the solver.

In [2]:
df_lp = pd.read_csv("../data/processed/lp_coefficients.csv")
df_lp.head()

,data_channel_is_lifestyle,data_channel_is_entertainment,data_channel_is_bus,data_channel_is_socmed,data_channel_is_tech,data_channel_is_world,data_channel_is_other,weekday_is_monday,weekday_is_tuesday,weekday_is_wednesday,...,LDA_02,LDA_03,LDA_04,global_subjectivity,global_sentiment_polarity,global_rate_positive_words,avg_positive_polarity,title_subjectivity,title_sentiment_polarity,pred_shares
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,-0.587577,-0.588251,0.979164,0.238790,0.418756,0.100166,-0.191671,-0.871396,-0.266541,7.528318
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.388686,-0.690085,1.310549,0.295554,0.042987,-0.335331,0.633394,-0.871396,-0.266541,7.440972
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,-0.646748,2.183039,-0.694212,0.676822,-2.919804,-1.286257,1.101772,-0.871396,-0.266541,7.912108
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,-0.646747,-0.081042,-0.692527,-0.327813,-1.299469,-1.604775,1.400703,0.361687,-1.203750,7.495076
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,-0.676216,-0.672492,1.640564,-0.217081,-0.612388,-0.268254,-0.479656,-0.254855,-0.641425,7.321684

In [3]:
shares = df_lp["pred_shares"].to_numpy()
lifestyle_indicator = df_lp[" data_channel_is_lifestyle"].to_numpy()
entertainment_indicator = df_lp[" data_channel_is_entertainment"].to_numpy()
bus_indicator = df_lp[" data_channel_is_bus"].to_numpy()
socmed_indicator = df_lp[" data_channel_is_socmed"].to_numpy()
tech_indicator = df_lp[" data_channel_is_tech"].to_numpy()
world_indicator = df_lp[" data_channel_is_world"].to_numpy()
other_indicator = df_lp[" data_channel_is_other"].to_numpy()

## Solver Implementation
Optimize news popularity under topic diversity constraints where each topic has to appear at least once.

In [4]:
from src.optimization.lp_solver import news_solver

In [5]:
# def news_solver(
#         shares,
#         lifestyle_indicator,
#         entertainment_indicator,
#         bus_indicator,
#         socmed_indicator,
#         tech_indicator,
#         world_indicator,
#         other_indicator,
#         K=10,
#         lower_bound=0,
#         solver_name="PULP_CBC_CMD",
#         verbose=False
# ):
#     """
#     Build ILP model for news article selection that maximize shares and maintain topic diversity.

#     Parameters
#     ----------
#     popularity : array-like, shape (N,)
#         (Predicted) raw shares
#     *_indicator : array-like, shape (N,)
#         1 if article is classified as each in the category list, 0 otherwise
#     K : int
#         Number of articles to select
    
#     Return
#     ----------
#     selected_indices: list
#         List of selected optimal indices
#     status: str
#         Solver status
#     """
#     N = len(shares)
    
#     # Model
#     model = pulp.LpProblem("News Selection", pulp.LpMaximize)
    
#     # Decision Variables
#     x = pulp.LpVariable.dicts("select", range(N), cat="Binary")

#     # Objective
#     model += pulp.lpSum(
#         (shares[i] * x[i] for i in range(N)))

#     # Capacity constraints
#     model += pulp.lpSum(x[i] for i in range(N)) == K

#     # Topic constraints 
#     model += pulp.lpSum(lifestyle_indicator[i] * x[i] for i in range(N)) >= lower_bound
#     model += pulp.lpSum(entertainment_indicator[i] * x[i] for i in range(N)) >= lower_bound
#     model += pulp.lpSum(bus_indicator[i] * x[i] for i in range(N)) >= lower_bound
#     model += pulp.lpSum(socmed_indicator[i] * x[i] for i in range(N)) >= lower_bound
#     model += pulp.lpSum(tech_indicator[i] * x[i] for i in range(N)) >= lower_bound
#     model += pulp.lpSum(world_indicator[i] * x[i] for i in range(N)) >= lower_bound
#     model += pulp.lpSum(other_indicator[i] * x[i] for i in range(N)) >= lower_bound

#     # Choose solver
#     if solver_name == "PULP_CBC_CMD":
#         solver = pulp.PULP_CBC_CMD(msg=verbose)
#     else:
#         raise ValueError(f"Unsupported Solver:{solver_name}")
    
#     # Solve
#     model.solve(solver)

#     status = pulp.LpStatus[model.status]

#     if status != "Optimal":
#         print(f"Warning: Solver status = {status}")
    
#     # Extract solution
#     selected_indices = [
#         i for i, var in x.items() if var.value() == 1
#     ]
#     return selected_indices, status

In [6]:
selected_indices, status = news_solver(
        shares=shares,
        lifestyle_indicator=lifestyle_indicator,
        entertainment_indicator=entertainment_indicator,
        bus_indicator=bus_indicator,
        socmed_indicator=socmed_indicator,
        tech_indicator=tech_indicator,
        world_indicator=world_indicator,
        other_indicator=other_indicator,
)

print(f"List of articles selected: {selected_indices}")

/home/codespace/.local/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

List of articles selected: [854, 2136, 2416, 2603, 2669, 3202, 6231, 6395, 6817, 7344]

In [7]:
lp_shares = df_lp.iloc[selected_indices]['pred_shares'].sum()
print(f"Optimal Shares by Linear Programming: {lp_shares: .5f} shares")
top10_shares = df_lp.sort_values('pred_shares', ascending=False)['pred_shares'].head(10).sum()
print(f"Optimal Shares by Naive Top 10 Selection: {top10_shares} shares")

Optimal Shares by Linear Programming:  85.68302 shares
Optimal Shares by Naive Top 10 Selection: 85.683019 shares

We solve this model across multiple random seeds (via re-trained XGBoost models) to assess:

- Stability of selected sets
- Opportunity cost relative to naive top-10 selection

In [8]:
import yaml

# Load configuration
with open('../config.yaml', 'r') as file:
    config = yaml.safe_load(file)

In [9]:
# Load dataset
df = load_data()

In [10]:
config['model']['params']

{'objective': 'reg:squarederror',
 'n_estimators': 100,
 'max_depth': 6,
 'learning_rate': 0.1,
 'subsample': 0.8,
 'colsample_bytree': 0.8,
 'random_state': 42}

In [11]:
random_seeds = [s for s in range(0,100, 10)]
df_sensitivity = []

for seed in random_seeds:
    X_train, X_test, y_train, y_test, categories_features = preprocess_features(df, random_state=seed)
    params = config['model']['params']
    params['random_state'] = seed
    xgb_model = xgb_train(X_train, 
                          y_train, 
                          **params)
    y_pred = xgb_predict(xgb_model, X_test)
    pred_df = X_test.copy()
    pred_df["pred_shares"] = y_pred
    
    # Convert to numpy array
    shares = pred_df["pred_shares"].to_numpy()
    lifestyle_indicator = pred_df[" data_channel_is_lifestyle"].to_numpy()
    entertainment_indicator = pred_df[" data_channel_is_entertainment"].to_numpy()
    bus_indicator = pred_df[" data_channel_is_bus"].to_numpy()
    socmed_indicator = pred_df[" data_channel_is_socmed"].to_numpy()
    tech_indicator = pred_df[" data_channel_is_tech"].to_numpy()
    world_indicator = pred_df[" data_channel_is_world"].to_numpy()
    other_indicator = pred_df[" data_channel_is_other"].to_numpy()

    # Apply ILP
    selected_indices, status = news_solver(
        shares,
        lifestyle_indicator,
        entertainment_indicator,
        bus_indicator,
        socmed_indicator,
        tech_indicator,
        world_indicator,
        other_indicator,
        K=10,
        lower_bound=1,
        solver_name="PULP_CBC_CMD",
        verbose=False)

    # Evaluate
    print(f"Seed ={seed}")
    top10_shares = pred_df.sort_values('pred_shares', ascending=False)['pred_shares'].head(10).sum()
    print(f"Optimal Shares by Naive Top 10 Selection: {top10_shares} shares")
    lp_shares = pred_df.iloc[selected_indices]['pred_shares'].sum()
    print(f"Optimal Shares by Linear Programming: {lp_shares} shares\n")

    # Sensitivity Analysis
    df_sensitivity.append({
        "seed": seed,
        "n_lifestyle_articles": pred_df.iloc[selected_indices][' data_channel_is_lifestyle'].sum(),
        "n_entertainment_articles": pred_df.iloc[selected_indices][' data_channel_is_entertainment'].sum(),                              
        "n_bus_articles" : pred_df.iloc[selected_indices][' data_channel_is_bus'].sum(),
        "n_socmed_articles": pred_df.iloc[selected_indices][' data_channel_is_socmed'].sum(),
        "n_tech_articles" : pred_df.iloc[selected_indices][' data_channel_is_tech'].sum(),
        "n_world_articles": pred_df.iloc[selected_indices][' data_channel_is_world'].sum(),
        "n_other_articles" : pred_df.iloc[selected_indices][' data_channel_is_other'].sum(),
        "shares_trade_off" : top10_shares - lp_shares})

ValueError: not enough values to unpack (expected 5, got 4)

In [ ]:
df_sensitivity = pd.DataFrame(df_sensitivity)
df_sensitivity

,seed,n_lifestyle_articles,n_entertainment_articles,n_bus_articles,n_socmed_articles,n_tech_articles,n_world_articles,n_other_articles,shares_trade_off
0,0,1.0,1.0,1.0,1.0,2.0,1.0,3.0,0.518250
1,10,2.0,1.0,1.0,3.0,1.0,1.0,1.0,0.570923
2,20,1.0,1.0,1.0,1.0,1.0,1.0,4.0,0.616570
3,30,1.0,1.0,2.0,1.0,1.0,1.0,3.0,0.931213
4,40,1.0,1.0,1.0,1.0,1.0,1.0,4.0,1.291252
5,50,1.0,1.0,1.0,1.0,1.0,1.0,4.0,0.970474
6,60,1.0,1.0,1.0,1.0,1.0,1.0,4.0,0.383347
7,70,1.0,1.0,1.0,1.0,1.0,1.0,4.0,0.501259
8,80,1.0,1.0,1.0,1.0,1.0,1.0,4.0,0.619995
9,90,2.0,1.0,1.0,2.0,1.0,1.0,2.0,0.337280

We conduct a sensitivity analysis by repeatedly solving the optimization problem under stochastic variations in predicted article popularity. Across all seeds, the LP solution exhibits stable topic allocation patterns, indicating robustness to prediction noise. Enforcing topic diversity incurs an average loss of approximately 0.5 predicted shares relative to a greedy top-K baseline, quantifying the efficiency–diversity trade-off.

In [ ]:
df_sensitivity.to_csv("../data/processed/df_sensitivity.csv", index=False)

## Extended Solver Implementation

In [ ]:
random_seeds = [s for s in range(0,100, 10)]
categories =[c for c in df.columns if c.startswith(" data_channel_is")]
extended_df_sensitivity = []

for diversity_lower_bound in range(1, len(categories) + 1):
    for seed in random_seeds:
        # Predict Shares
        X_train, X_test, y_train, y_test, categories_features = preprocess_features(df, random_state=seed)
        params = config['model']['params']
        params['random_state'] = seed
        xgb_model = xgb_train(X_train, 
                            y_train, 
                            **params)
        y_pred = xgb_predict(xgb_model, X_test)
        pred_df = X_test.copy()
        pred_df["pred_shares"] = y_pred

        
        # Convert to numpy array
        shares = pred_df["pred_shares"].to_numpy()
        lifestyle_indicator = pred_df[" data_channel_is_lifestyle"].to_numpy()
        entertainment_indicator = pred_df[" data_channel_is_entertainment"].to_numpy()
        bus_indicator = pred_df[" data_channel_is_bus"].to_numpy()
        socmed_indicator = pred_df[" data_channel_is_socmed"].to_numpy()
        tech_indicator = pred_df[" data_channel_is_tech"].to_numpy()
        world_indicator = pred_df[" data_channel_is_world"].to_numpy()
        other_indicator = pred_df[" data_channel_is_other"].to_numpy()

        # Apply ILP
        selected_indices, status = extended_news_solver(
            shares,
            lifestyle_indicator,
            entertainment_indicator,
            bus_indicator,
            socmed_indicator,
            tech_indicator,
            world_indicator,
            other_indicator,
            K=10,
            diversity_lower_bound=diversity_lower_bound,
            solver_name="PULP_CBC_CMD",
            verbose=False)
        # Evaluate
        print(f"Seed ={seed}")
        print(f"Required minimum of Topics ={diversity_lower_bound}")
        top10_shares = pred_df.sort_values('pred_shares', ascending=False)['pred_shares'].head(10).sum()
        print(f"Optimal Shares by Naive Top 10 Selection: {top10_shares} shares")
        lp_shares = pred_df.iloc[selected_indices]['pred_shares'].sum()
        print(f"Optimal Shares by Linear Programming: {lp_shares} shares\n")
    
        # Sensitivity Analysis
        extended_df_sensitivity.append({
            "min_topics" : diversity_lower_bound,
            "seed": seed,
            "n_lifestyle_articles": pred_df.iloc[selected_indices][' data_channel_is_lifestyle'].sum(),
            "n_entertainment_articles": pred_df.iloc[selected_indices][' data_channel_is_entertainment'].sum(),                              
            "n_bus_articles" : pred_df.iloc[selected_indices][' data_channel_is_bus'].sum(),
            "n_socmed_articles": pred_df.iloc[selected_indices][' data_channel_is_socmed'].sum(),
            "n_tech_articles" : pred_df.iloc[selected_indices][' data_channel_is_tech'].sum(),
            "n_world_articles": pred_df.iloc[selected_indices][' data_channel_is_world'].sum(),
            "n_other_articles" : pred_df.iloc[selected_indices][' data_channel_is_other'].sum(),
            "realized_diversity" : (
            int(pred_df.iloc[selected_indices][' data_channel_is_lifestyle'].sum() > 0) +
            int(pred_df.iloc[selected_indices][' data_channel_is_entertainment'].sum() > 0) +
            int(pred_df.iloc[selected_indices][' data_channel_is_bus'].sum() > 0) +
            int(pred_df.iloc[selected_indices][' data_channel_is_socmed'].sum() > 0) +
            int(pred_df.iloc[selected_indices][' data_channel_is_tech'].sum() > 0) +
            int(pred_df.iloc[selected_indices][' data_channel_is_world'].sum() > 0) +
            int(pred_df.iloc[selected_indices][' data_channel_is_other'].sum() > 0)),
            "lp_shares": lp_shares,
            "shares_trade_off" : top10_shares - lp_shares})

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =0
Required minimum of Topics =1
Optimal Shares by Naive Top 10 Selection: 88.36805725097656 shares
Optimal Shares by Linear Programming: 88.36805725097656 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =10
Required minimum of Topics =1
Optimal Shares by Naive Top 10 Selection: 88.62506866455078 shares
Optimal Shares by Linear Programming: 88.62506103515625 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =20
Required minimum of Topics =1
Optimal Shares by Naive Top 10 Selection: 89.95726013183594 shares
Optimal Shares by Linear Programming: 89.9572525024414 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =30
Required minimum of Topics =1
Optimal Shares by Naive Top 10 Selection: 89.28369140625 shares
Optimal Shares by Linear Programming: 89.28369140625 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =40
Required minimum of Topics =1
Optimal Shares by Naive Top 10 Selection: 89.3552474975586 shares
Optimal Shares by Linear Programming: 89.3552474975586 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =50
Required minimum of Topics =1
Optimal Shares by Naive Top 10 Selection: 88.34233856201172 shares
Optimal Shares by Linear Programming: 88.34233093261719 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =60
Required minimum of Topics =1
Optimal Shares by Naive Top 10 Selection: 89.764404296875 shares
Optimal Shares by Linear Programming: 89.76441192626953 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =70
Required minimum of Topics =1
Optimal Shares by Naive Top 10 Selection: 87.88523864746094 shares
Optimal Shares by Linear Programming: 87.88523864746094 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =80
Required minimum of Topics =1
Optimal Shares by Naive Top 10 Selection: 88.40774536132812 shares
Optimal Shares by Linear Programming: 88.4077377319336 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =90
Required minimum of Topics =1
Optimal Shares by Naive Top 10 Selection: 88.49375915527344 shares
Optimal Shares by Linear Programming: 88.49375915527344 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =0
Required minimum of Topics =2
Optimal Shares by Naive Top 10 Selection: 88.36805725097656 shares
Optimal Shares by Linear Programming: 88.36805725097656 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =10
Required minimum of Topics =2
Optimal Shares by Naive Top 10 Selection: 88.62506866455078 shares
Optimal Shares by Linear Programming: 88.62506103515625 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =20
Required minimum of Topics =2
Optimal Shares by Naive Top 10 Selection: 89.95726013183594 shares
Optimal Shares by Linear Programming: 89.9572525024414 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =30
Required minimum of Topics =2
Optimal Shares by Naive Top 10 Selection: 89.28369140625 shares
Optimal Shares by Linear Programming: 89.28369140625 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =40
Required minimum of Topics =2
Optimal Shares by Naive Top 10 Selection: 89.3552474975586 shares
Optimal Shares by Linear Programming: 89.3552474975586 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =50
Required minimum of Topics =2
Optimal Shares by Naive Top 10 Selection: 88.34233856201172 shares
Optimal Shares by Linear Programming: 88.34233093261719 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =60
Required minimum of Topics =2
Optimal Shares by Naive Top 10 Selection: 89.764404296875 shares
Optimal Shares by Linear Programming: 89.76441192626953 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =70
Required minimum of Topics =2
Optimal Shares by Naive Top 10 Selection: 87.88523864746094 shares
Optimal Shares by Linear Programming: 87.88523864746094 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =80
Required minimum of Topics =2
Optimal Shares by Naive Top 10 Selection: 88.40774536132812 shares
Optimal Shares by Linear Programming: 88.4077377319336 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =90
Required minimum of Topics =2
Optimal Shares by Naive Top 10 Selection: 88.49375915527344 shares
Optimal Shares by Linear Programming: 88.49375915527344 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =0
Required minimum of Topics =3
Optimal Shares by Naive Top 10 Selection: 88.36805725097656 shares
Optimal Shares by Linear Programming: 88.36805725097656 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =10
Required minimum of Topics =3
Optimal Shares by Naive Top 10 Selection: 88.62506866455078 shares
Optimal Shares by Linear Programming: 88.62506103515625 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =20
Required minimum of Topics =3
Optimal Shares by Naive Top 10 Selection: 89.95726013183594 shares
Optimal Shares by Linear Programming: 89.9572525024414 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =30
Required minimum of Topics =3
Optimal Shares by Naive Top 10 Selection: 89.28369140625 shares
Optimal Shares by Linear Programming: 89.28369140625 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =40
Required minimum of Topics =3
Optimal Shares by Naive Top 10 Selection: 89.3552474975586 shares
Optimal Shares by Linear Programming: 89.33806610107422 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =50
Required minimum of Topics =3
Optimal Shares by Naive Top 10 Selection: 88.34233856201172 shares
Optimal Shares by Linear Programming: 88.301513671875 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =60
Required minimum of Topics =3
Optimal Shares by Naive Top 10 Selection: 89.764404296875 shares
Optimal Shares by Linear Programming: 89.76441192626953 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =70
Required minimum of Topics =3
Optimal Shares by Naive Top 10 Selection: 87.88523864746094 shares
Optimal Shares by Linear Programming: 87.88523864746094 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =80
Required minimum of Topics =3
Optimal Shares by Naive Top 10 Selection: 88.40774536132812 shares
Optimal Shares by Linear Programming: 88.4077377319336 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =90
Required minimum of Topics =3
Optimal Shares by Naive Top 10 Selection: 88.49375915527344 shares
Optimal Shares by Linear Programming: 88.49375915527344 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =0
Required minimum of Topics =4
Optimal Shares by Naive Top 10 Selection: 88.36805725097656 shares
Optimal Shares by Linear Programming: 88.36805725097656 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =10
Required minimum of Topics =4
Optimal Shares by Naive Top 10 Selection: 88.62506866455078 shares
Optimal Shares by Linear Programming: 88.62506103515625 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =20
Required minimum of Topics =4
Optimal Shares by Naive Top 10 Selection: 89.95726013183594 shares
Optimal Shares by Linear Programming: 89.9572525024414 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =30
Required minimum of Topics =4
Optimal Shares by Naive Top 10 Selection: 89.28369140625 shares
Optimal Shares by Linear Programming: 89.28369140625 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =40
Required minimum of Topics =4
Optimal Shares by Naive Top 10 Selection: 89.3552474975586 shares
Optimal Shares by Linear Programming: 89.27851104736328 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =50
Required minimum of Topics =4
Optimal Shares by Naive Top 10 Selection: 88.34233856201172 shares
Optimal Shares by Linear Programming: 88.1585922241211 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =60
Required minimum of Topics =4
Optimal Shares by Naive Top 10 Selection: 89.764404296875 shares
Optimal Shares by Linear Programming: 89.76441192626953 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =70
Required minimum of Topics =4
Optimal Shares by Naive Top 10 Selection: 87.88523864746094 shares
Optimal Shares by Linear Programming: 87.88523864746094 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =80
Required minimum of Topics =4
Optimal Shares by Naive Top 10 Selection: 88.40774536132812 shares
Optimal Shares by Linear Programming: 88.4077377319336 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =90
Required minimum of Topics =4
Optimal Shares by Naive Top 10 Selection: 88.49375915527344 shares
Optimal Shares by Linear Programming: 88.49375915527344 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =0
Required minimum of Topics =5
Optimal Shares by Naive Top 10 Selection: 88.36805725097656 shares
Optimal Shares by Linear Programming: 88.313232421875 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =10
Required minimum of Topics =5
Optimal Shares by Naive Top 10 Selection: 88.62506866455078 shares
Optimal Shares by Linear Programming: 88.58345031738281 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =20
Required minimum of Topics =5
Optimal Shares by Naive Top 10 Selection: 89.95726013183594 shares
Optimal Shares by Linear Programming: 89.80904388427734 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =30
Required minimum of Topics =5
Optimal Shares by Naive Top 10 Selection: 89.28369140625 shares
Optimal Shares by Linear Programming: 89.15483856201172 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =40
Required minimum of Topics =5
Optimal Shares by Naive Top 10 Selection: 89.3552474975586 shares
Optimal Shares by Linear Programming: 89.05644226074219 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =50
Required minimum of Topics =5
Optimal Shares by Naive Top 10 Selection: 88.34233856201172 shares
Optimal Shares by Linear Programming: 87.9533462524414 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =60
Required minimum of Topics =5
Optimal Shares by Naive Top 10 Selection: 89.764404296875 shares
Optimal Shares by Linear Programming: 89.71917724609375 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =70
Required minimum of Topics =5
Optimal Shares by Naive Top 10 Selection: 87.88523864746094 shares
Optimal Shares by Linear Programming: 87.88523864746094 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =80
Required minimum of Topics =5
Optimal Shares by Naive Top 10 Selection: 88.40774536132812 shares
Optimal Shares by Linear Programming: 88.35982513427734 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =90
Required minimum of Topics =5
Optimal Shares by Naive Top 10 Selection: 88.49375915527344 shares
Optimal Shares by Linear Programming: 88.48937225341797 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =0
Required minimum of Topics =6
Optimal Shares by Naive Top 10 Selection: 88.36805725097656 shares
Optimal Shares by Linear Programming: 88.11405944824219 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =10
Required minimum of Topics =6
Optimal Shares by Naive Top 10 Selection: 88.62506866455078 shares
Optimal Shares by Linear Programming: 88.37193298339844 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =20
Required minimum of Topics =6
Optimal Shares by Naive Top 10 Selection: 89.95726013183594 shares
Optimal Shares by Linear Programming: 89.63964080810547 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =30
Required minimum of Topics =6
Optimal Shares by Naive Top 10 Selection: 89.28369140625 shares
Optimal Shares by Linear Programming: 88.8629150390625 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =40
Required minimum of Topics =6
Optimal Shares by Naive Top 10 Selection: 89.3552474975586 shares
Optimal Shares by Linear Programming: 88.7008056640625 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =50
Required minimum of Topics =6
Optimal Shares by Naive Top 10 Selection: 88.34233856201172 shares
Optimal Shares by Linear Programming: 87.70073699951172 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =60
Required minimum of Topics =6
Optimal Shares by Naive Top 10 Selection: 89.764404296875 shares
Optimal Shares by Linear Programming: 89.59515380859375 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =70
Required minimum of Topics =6
Optimal Shares by Naive Top 10 Selection: 87.88523864746094 shares
Optimal Shares by Linear Programming: 87.6731948852539 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =80
Required minimum of Topics =6
Optimal Shares by Naive Top 10 Selection: 88.40774536132812 shares
Optimal Shares by Linear Programming: 88.12126159667969 shares

/usr/local/python/3.12.1/lib/python3.12/site-packages/pulp/pulp.py:1489: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")

Seed =90
Required minimum of Topics =6
Optimal Shares by Naive Top 10 Selection: 88.49375915527344 shares
Optimal Shares by Linear Programming: 88.41136932373047 shares

In [ ]:
extended_df_sensitivity = pd.DataFrame(extended_df_sensitivity)
extended_df_sensitivity

,min_topics,seed,n_lifestyle_articles,n_entertainment_articles,n_bus_articles,n_socmed_articles,n_tech_articles,n_world_articles,n_other_articles,realized_diversity,lp_shares,shares_trade_off
0,1,0,1.0,0.0,0.0,3.0,2.0,0.0,4.0,4,88.368057,0.000000
1,1,10,2.0,0.0,1.0,4.0,0.0,0.0,3.0,4,88.625061,0.000008
2,1,20,1.0,0.0,1.0,1.0,0.0,0.0,7.0,4,89.957253,0.000008
3,1,30,0.0,1.0,2.0,1.0,0.0,0.0,6.0,4,89.283691,0.000000
4,1,40,0.0,0.0,0.0,3.0,0.0,0.0,7.0,2,89.355247,0.000000
5,1,50,0.0,0.0,0.0,3.0,0.0,0.0,7.0,2,88.342331,0.000008
6,1,60,0.0,0.0,1.0,2.0,1.0,0.0,6.0,4,89.764412,-0.000008
7,1,70,1.0,0.0,1.0,2.0,1.0,0.0,5.0,5,87.885239,0.000000
8,1,80,0.0,1.0,1.0,2.0,0.0,0.0,6.0,4,88.407738,0.000008
9,1,90,2.0,2.0,0.0,2.0,0.0,0.0,4.0,4,88.493759,0.000000
10,2,0,1.0,0.0,0.0,3.0,2.0,0.0,4.0,4,88.368057,0.000000
11,2,10,2.0,0.0,1.0,4.0,0.0,0.0,3.0,4,88.625061,0.000008
12,2,20,1.0,0.0,1.0,1.0,0.0,0.0,7.0,4,89.957253,0.000008
13,2,30,0.0,1.0,2.0,1.0,0.0,0.0,6.0,4,89.283691,0.000000
14,2,40,0.0,0.0,0.0,3.0,0.0,0.0,7.0,2,89.355247,0.000000
15,2,50,0.0,0.0,0.0,3.0,0.0,0.0,7.0,2,88.342331,0.000008
16,2,60,0.0,0.0,1.0,2.0,1.0,0.0,6.0,4,89.764412,-0.000008
17,2,70,1.0,0.0,1.0,2.0,1.0,0.0,5.0,5,87.885239,0.000000
18,2,80,0.0,1.0,1.0,2.0,0.0,0.0,6.0,4,88.407738,0.000008
19,2,90,2.0,2.0,0.0,2.0,0.0,0.0,4.0,4,88.493759,0.000000
20,3,0,1.0,0.0,0.0,3.0,2.0,0.0,4.0,4,88.368057,0.000000
21,3,10,2.0,0.0,1.0,4.0,0.0,0.0,3.0,4,88.625061,0.000008
22,3,20,1.0,0.0,1.0,1.0,0.0,0.0,7.0,4,89.957253,0.000008
23,3,30,0.0,1.0,2.0,1.0,0.0,0.0,6.0,4,89.283691,0.000000
24,3,40,0.0,0.0,1.0,2.0,0.0,0.0,7.0,3,89.338066,0.017181
25,3,50,0.0,0.0,0.0,3.0,1.0,0.0,6.0,3,88.301514,0.040825
26,3,60,0.0,0.0,1.0,2.0,1.0,0.0,6.0,4,89.764412,-0.000008
27,3,70,1.0,0.0,1.0,2.0,1.0,0.0,5.0,5,87.885239,0.000000
28,3,80,0.0,1.0,1.0,2.0,0.0,0.0,6.0,4,88.407738,0.000008
29,3,90,2.0,2.0,0.0,2.0,0.0,0.0,4.0,4,88.493759,0.000000
30,4,0,1.0,0.0,0.0,3.0,2.0,0.0,4.0,4,88.368057,0.000000
31,4,10,2.0,0.0,1.0,4.0,0.0,0.0,3.0,4,88.625061,0.000008
32,4,20,1.0,0.0,1.0,1.0,0.0,0.0,7.0,4,89.957253,0.000008
33,4,30,0.0,1.0,2.0,1.0,0.0,0.0,6.0,4,89.283691,0.000000
34,4,40,1.0,0.0,1.0,1.0,0.0,0.0,7.0,4,89.278511,0.076736
35,4,50,0.0,0.0,1.0,3.0,1.0,0.0,5.0,4,88.158592,0.183746
36,4,60,0.0,0.0,1.0,2.0,1.0,0.0,6.0,4,89.764412,-0.000008
37,4,70,1.0,0.0,1.0,2.0,1.0,0.0,5.0,5,87.885239,0.000000
38,4,80,0.0,1.0,1.0,2.0,0.0,0.0,6.0,4,88.407738,0.000008
39,4,90,2.0,2.0,0.0,2.0,0.0,0.0,4.0,4,88.493759,0.000000
40,5,0,1.0,1.0,0.0,2.0,2.0,0.0,4.0,5,88.313232,0.054825
41,5,10,2.0,0.0,1.0,3.0,1.0,0.0,3.0,5,88.583450,0.041618
42,5,20,1.0,0.0,1.0,1.0,0.0,1.0,6.0,5,89.809044,0.148216
43,5,30,1.0,1.0,2.0,1.0,0.0,0.0,5.0,5,89.154839,0.128853
44,5,40,1.0,1.0,1.0,1.0,0.0,0.0,6.0,5,89.056442,0.298805
45,5,50,0.0,1.0,1.0,2.0,1.0,0.0,5.0,5,87.953346,0.388992
46,5,60,0.0,1.0,1.0,1.0,1.0,0.0,6.0,5,89.719177,0.045227
47,5,70,1.0,0.0,1.0,2.0,1.0,0.0,5.0,5,87.885239,0.000000
48,5,80,1.0,1.0,1.0,1.0,0.0,0.0,6.0,5,88.359825,0.047920
49,5,90,2.0,2.0,0.0,2.0,1.0,0.0,3.0,5,88.489372,0.004387
50,6,0,1.0,1.0,1.0,2.0,2.0,0.0,3.0,6,88.114059,0.253998
51,6,10,2.0,1.0,1.0,3.0,1.0,0.0,2.0,6,88.371933,0.253136
52,6,20,1.0,1.0,1.0,1.0,0.0,1.0,5.0,6,89.639641,0.317619
53,6,30,1.0,1.0,2.0,1.0,1.0,0.0,4.0,6,88.862915,0.420776
54,6,40,1.0,1.0,1.0,1.0,1.0,0.0,5.0,6,88.700806,0.654442
55,6,50,0.0,1.0,1.0,1.0,1.0,1.0,5.0,6,87.700737,0.641602
56,6,60,1.0,1.0,1.0,1.0,1.0,0.0,5.0,6,89.595154,0.169250
57,6,70,1.0,1.0,1.0,2.0,1.0,0.0,4.0,6,87.673195,0.212044
58,6,80,1.0,1.0,1.0,1.0,1.0,0.0,5.0,6,88.121262,0.286484
59,6,90,2.0,2.0,1.0,2.0,1.0,0.0,2.0,6,88.411369,0.082390

In [ ]:
extended_df_sensitivity.to_csv("../data/processed/df_extended_sensitivity.csv", index=False)